FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y gnupg wget lsb-release && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    wget https://repo.mysql.com/mysql-apt-config_0.8.30-1_all.deb && \
    dpkg -i mysql-apt-config_0.8.30-1_all.deb && \
    apt-get update && \
    apt-get install -y mysql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /data

CMD ["bash"]
