ARG PHP_VERSION

FROM php:${PHP_VERSION}-fpm-alpine

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
ENV COMPOSER_HOME="/usr/local/composer"
# Get psalm
ARG PHP_PSALM_VERSION
RUN composer global require vimeo/psalm:$PHP_PSALM_VERSION
ENV PATH="${PATH}:${COMPOSER_HOME}/vendor/bin"
